---
- name: Install Roles from Galaxy
  hosts: localhost
  connection: local
  become_user: "jenkins"
  become: yes
  tasks:
    - name: installing ansible-galaxy roles
      command: ansible-galaxy install -r requirements.yml --roles-path roles

- name: Install Java
  hosts: "{{ variable_host | default('app_server') }}"
  become: yes
  become_user: jenkins
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: "{{ variable_host | default('app_server') }}"
  tasks:
    - get_url:
        force: yes
        url: "{{ ARTIFACT_URL }}"
        dest: "/tmp/{{ APP_NAME }}.war"
    - stat: 
        path: "/tmp/{{ APP_NAME }}.war"

- name: Setup Spring Boot
  hosts: "{{ variable_host | default('app_server') }}"
  become: yes
  become_user: jenkins
  roles: 
    - { role: pellepelster.springboot-role,
        spring_boot_file: "{{ APP_NAME }}.war",
        spring_boot_file_source: "/tmp/{{ APP_NAME }}.war",
        spring_boot_application_id: "{{ APP_NAME }}",
        spring_boot_http_port: '8090' 
    } 
