---
- name: Install Java
  hosts: app_server
  become: yes
  become_user: root
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: app_server
  become_user: root
  become: yes
  tasks:
    - get_url: 
        force: yes
        url: "http://54.70.187.156:8081/repository/demoapp-rele/br/com/meetup/ansible/soccer-stats/0.0.2-57/soccer-stats-0.0.2-57.war"
        dest: "/tmp/soccer-stats.war"
    - stat: 
        path: "/tmp/soccer-stats.war"

- name: Setup Spring Boot
  hosts: app_server
  become: yes
  become_user: root
  roles: 
    - { role: pellepelster.springboot-role,
        spring_boot_file: "{{ APP_NAME }}.war",
        spring_boot_file_source: "/tmp/{{ APP_NAME }}.war",
        spring_boot_application_id: "{{ APP_NAME }}"
    } 
